### ISSUE TITLE
Upgrade to jekyll-toc 0.3

### ISSUE THREAD

**Issue by mide** [mide/mide.io#5]
In the change from `0.2` to `0.3`, [jekyll-toc](https://github.com/toshimaru/jekyll-toc) added nested lists. I previously adjusted the TOC via CSS to get a nested look.
```css
  ul.section-nav {
    padding: 0px;
    list-style-position: inside;
    list-style-type: none;
    // H1 is used only for page titles, so we start at H2.
    .toc-h1{padding-left: 0px;}
    .toc-h2{padding-left: 0px;}
    .toc-h3{padding-left: 25px;}
    .toc-h4{padding-left: 50px;}
    .toc-h5{padding-left: 75px;}
    .toc-h6{padding-left: 100px;}
  }
```

With the new change, the CSS needs to be adjusted. See [their upgrade guide](https://github.com/toshimaru/jekyll-toc/wiki/0.3-Upgrade-Guide) for more info.
